### ISSUE TITLE
Incompatibility with conan2

### ISSUE THREAD

**Issue by vuntz** [centreon/centreon-clib#87]
While trying to build centreon-clib from sources on AlmaLinux 9, the build failed with:

```
======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /home/almalinux/centreon-clib
ERROR: Invalid generator 'cmake_find_package'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps
```
Quickly searching for this led me to https://stackoverflow.com/questions/75794398/conan-returning-error-invalid-generator-cmake-when-running-conan-install

Changing the pip install command in cmake.sh to install conan<2.0 fixed it. Since Conan 2.0 is relatively fresh (https://blog.conan.io/2023/02/22/Conan-2.0.html), it appears centreon-clib has not been migrated to it yet. We should either fix the pip install line, or migrate to Conan 2.0.

**Comment by bouda1** [comment]
Be careful, this repository is deprecated. Please switch to https://github.com/centreon/centreon-collect
